server:
  port: 8090

upload:
  key: dXBsb2FkLTMtYmVpamluZy0xMjM0NTY=
#  url: https://admin.myfreecloud.cn/apis/radar/file/savefile
  url: http://localhost:8080/radar/file/savefile

monitor:
  dir: D:\monitorTest\

logging:
  level:
    cn:
      myfreecloud: trace
  file:
    path: C:/radarFileUpload/log
#logging:
#  level:
#    cn:
#      myfreecloud: trace
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} === [%thread] === %-5level === %logger{50} ==== %msg%n'
#  file:
#    path: /spring/log